version: '3.7'

services:
  smartmeter-reader:
    restart: unless-stopped
    build: .
    privileged: true
    volumes:
      - .:/app
  web:
    image: gists/lighttpd
    restart: always
    ports:
      - "8088:80"
    volumes:
      - ./log:/var/www/smartmeter
    depends_on:
      - smartmeter-reader

